-- MySQL Script generated by MySQL Workbench
-- Mon Nov 15 19:14:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `Email` VARCHAR(70) NOT NULL,
  `Password` VARCHAR(65) NOT NULL,
  `Type` ENUM('Client', 'Doctor', 'Admin', 'Receptionist') NOT NULL DEFAULT 'Client',
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `ID_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `Notes` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Client_Account1_idx` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Account1`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Doctor_Account_idx` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_Account`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receptionist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receptionist` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Receptionist_Account1_idx` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Receptionist_Account1`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Admin_Account1_idx` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_Account1`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Treatment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Description` TEXT NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`Type`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DoctorQualifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DoctorQualifications` (
  `Doctor_ID` INT NOT NULL,
  `Treatment_ID` INT NOT NULL,
  `IsQualified` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Doctor_ID`, `Treatment_ID`),
  INDEX `fk_Doctor_has_Treatment_Treatment1_idx` (`Treatment_ID` ASC) VISIBLE,
  INDEX `fk_Doctor_has_Treatment_Doctor1_idx` (`Doctor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Doctor_has_Treatment_Doctor1`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `mydb`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Treatment_Treatment1`
    FOREIGN KEY (`Treatment_ID`)
    REFERENCES `mydb`.`Treatment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visit` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Client_ID` INT NOT NULL,
  `Doctor_ID` INT NOT NULL,
  `Treatment_Type` VARCHAR(45) NOT NULL,
  `Date` TIMESTAMP NOT NULL,
  `Notes` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID`, `Client_ID`, `Doctor_ID`, `Treatment_Type`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Visit_Client1_idx` (`Client_ID` ASC) VISIBLE,
  INDEX `fk_Visit_Treatment1_idx` (`Treatment_Type` ASC) VISIBLE,
  INDEX `fk_Visit_Doctor1_idx` (`Doctor_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Visit_Client1`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `mydb`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Treatment1`
    FOREIGN KEY (`Treatment_Type`)
    REFERENCES `mydb`.`Treatment` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Doctor1`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `mydb`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY 'admin';

GRANT ALL ON `mydb`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
