-- MySQL Script generated by MySQL Workbench
-- Sun Dec  5 16:20:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IcelandDental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IcelandDental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IcelandDental` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `IcelandDental` ;

-- -----------------------------------------------------
-- Table `IcelandDental`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Account` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(70) NOT NULL,
  `Password` VARCHAR(65) NOT NULL,
  `Type` ENUM('Client', 'Doctor', 'Admin', 'Receptionist') NOT NULL DEFAULT 'Client',
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcelandDental`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Client` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `Notes` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID`, `Email`),
  INDEX `fk_Client_Account1_idx` (`Email` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_Client_Account1`
    FOREIGN KEY (`Email`)
    REFERENCES `IcelandDental`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcelandDental`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Doctor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_Doctor_Account_idx` (`Email` ASC),
  CONSTRAINT `fk_Doctor_Account`
    FOREIGN KEY (`Email`)
    REFERENCES `IcelandDental`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcelandDental`.`Receptionist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Receptionist` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_Receptionist_Account1_idx` (`Email` ASC),
  CONSTRAINT `fk_Receptionist_Account1`
    FOREIGN KEY (`Email`)
    REFERENCES `IcelandDental`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcelandDental`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Admin` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Adress` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`ID`, `Email`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_Admin_Account1_idx` (`Email` ASC),
  CONSTRAINT `fk_Admin_Account1`
    FOREIGN KEY (`Email`)
    REFERENCES `IcelandDental`.`Account` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcelandDental`.`Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Treatment` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` TEXT NOT NULL,
  `Price` DECIMAL NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcelandDental`.`Visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Visit` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Client_ID` INT NOT NULL,
  `Doctor_ID` INT NOT NULL,
  `Treatment_ID` INT NOT NULL,
  `Date` TIMESTAMP NOT NULL,
  `Notes` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID`, `Client_ID`, `Doctor_ID`, `Treatment_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_Visit_Client1_idx` (`Client_ID` ASC),
  INDEX `fk_Visit_Doctor1_idx` (`Doctor_ID` ASC),
  INDEX `fk_Visit_Treatment1_idx` (`Treatment_ID` ASC),
  CONSTRAINT `fk_Visit_Client1`
    FOREIGN KEY (`Client_ID`)
    REFERENCES `IcelandDental`.`Client` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Doctor1`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `IcelandDental`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visit_Treatment1`
    FOREIGN KEY (`Treatment_ID`)
    REFERENCES `IcelandDental`.`Treatment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IcelandDental`.`Doctor_has_Treatment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IcelandDental`.`Doctor_has_Treatment` (
  `Doctor_ID` INT NOT NULL,
  `Treatment_ID` INT NOT NULL,
  `isQualified` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Doctor_ID`, `Treatment_ID`),
  INDEX `fk_Doctor_has_Treatment_Treatment1_idx` (`Treatment_ID` ASC),
  INDEX `fk_Doctor_has_Treatment_Doctor1_idx` (`Doctor_ID` ASC),
  CONSTRAINT `fk_Doctor_has_Treatment_Doctor1`
    FOREIGN KEY (`Doctor_ID`)
    REFERENCES `IcelandDental`.`Doctor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_has_Treatment_Treatment1`
    FOREIGN KEY (`Treatment_ID`)
    REFERENCES `IcelandDental`.`Treatment` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY 'StefHoga87';

GRANT ALL ON `IcelandDental`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
